### ISSUE TITLE
One doubt from your code.

### ISSUE THREAD

**Issue by mohit-madan** [Kylin9511/CRNet#4]
Why have you take the size of **nc_expand** in the evaluator function of your **statics.py** file to be **257**? Because usually for taking FFT, the input size is taken as multiples of 2. Is there any reason you have chosen **257** instead of **256**?
Please clarify.

**Comment by Kylin9511** [comment]
@mohit-madan 
First of all, I don't think 256 or 257 makes much difference here since an extra line of zero does not change the result of FFT much. In fact I think there suppose to be more lines of zero omitted since the FFT result has been precise enough.

The specific reason why I use 257 is that the original CsiNet project does so. The dataset and the corresponding criteria are directly refered from the original CsiNet project for fair comparison. Since the author of that project is also the author of the open source dataset, which hides all the FFT preprocessing details, the criteria rule should not be changed unless you establish a new dataset whose preprocessing details you are sure about.

Please refer to [The original CsiNet project](https://github.com/sydney222/Python_CsiNet/blob/8d84eb8d2d2b3a5ed6b66b60fa3a7943734bed8f/CsiNet_train.py#L144) if you are really confused.

> By the way, the key criteria is NMSE in CRNet paper, which has nothing to do with FFT at all. The nc_expand is preserved to maintain the integrity of the CRNet project.
